# Generated by Django 4.1.1 on 2023-01-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_active_order_is_active_address_is_active'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('method', models.CharField(max_length=50)),
                ('amount_total', models.PositiveIntegerField()),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('intent_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Stripe Payment',
                'verbose_name_plural': 'Stripe Payments',
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
