# Generated by Django 4.1.1 on 2023-01-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripepayment_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
