version: "3.9"

services:
  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    network_mode: host # localhost in stripe container now is the same as host localhost
    command: "listen --api-key ${STRIPE_SECRET_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to localhost:8000/payments/webhooks/stripe/"
    env_file:
      - .env
  web:
    build: .
    command:
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/urshop
    ports:
      # Local:Container
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14.5-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
