# Generated by Django 4.1.1 on 2022-10-20 17:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_alter_cart_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
    ]
