# Generated by Django 4.1.1 on 2022-10-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_alter_cart_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
            ],
        ),
    ]
