# Generated by Django 4.1.1 on 2022-10-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='users/'),
            preserve_default=False,
        ),
    ]
