# Generated by Django 4.1.1 on 2022-10-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('SHOPPER', 'Shopper'), ('SELLER', 'Seller')], default='SHOPPER', max_length=16),
        ),
    ]
