# Generated by Django 4.1.1 on 2022-10-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_address_address_type_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='zip',
        ),
    ]
