# Generated by Django 4.1.1 on 2022-10-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
