# Generated by Django 4.1.1 on 2023-01-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_active_order_is_active_address_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
    ]
