# Generated by Django 4.1.1 on 2023-01-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('BILLING', 'Billing address'), ('SHIPPING', 'Shipping address')], default='SHIPPING', max_length=16),
        ),
    ]
