# Generated by Django 4.1.1 on 2023-01-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_address_e_mail_address_first_name_address_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='e_mail',
            new_name='email',
        ),
    ]
