# Generated by Django 4.1.1 on 2022-10-03 16:21

from django.db import migrations, models
import products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, validators=[products.utils.product_quantity_validator]),
        ),
    ]
