# Generated by Django 4.1.1 on 2022-10-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=128, verbose_name='brand-name'),
        ),
    ]
